### ISSUE TITLE
Can't access MsViz

### ISSUE THREAD

**Issue by LasseLorentzen** [vitalit-sib/msviz-docker#1]
Hi, 

I'm trying to use your software, but I can't seem to access MsViz through my browser. I installed on a Wondows 7 PC, through docker as described in the readme. However when opening http://192.168.99.100:9001 I see the following:

![msviz](https://user-images.githubusercontent.com/21430519/29109798-a575d20e-7ce4-11e7-8722-dcbeb881042b.png)

I'm really not very familiar with working with servers, so I hope you can help me solve this issue

Kind regards,
Lasse

**Comment by rmylonas** [comment]
Hi Lasse,

You should also try with "localhost":
http://localhost:9001

I recently installed the Docker on a Windows 10 and had to use the localhost for the URL.

Please let me know if that works,
Roman

**Comment by LasseLorentzen** [comment]
Hi Roman,

Thank you for the quick response. I already tried using localhost without luck. Any other ideas?

Cheers,
Lasse

**Comment by rmylonas** [comment]
I guess that would have been to easy. :-)

Does your main folder contain this file structure?
_./msviz-frontend/htdocs/_

Within this folder you should find several files and folders (e.g. _index.html_).

If this is OK you should type `docker ps` on the command line. There should be 3 entries and all of them should have a status _UP_.  

If they're all up and running, you should have a look at the logs. The ouptut from `docker ps` gives you the _CONTAINER ID_ from the image _eboraas/apache_. The _CONTAINER ID_ should be something like _8eff0dd1bb7f_. Then you type `docker logs CONTAINER_ID`. 

The logs might help us.

**Comment by LasseLorentzen** [comment]
Yeah, things like this rarely are :(

htdocs contains the following:
![htdocs](https://user-images.githubusercontent.com/21430519/29155747-802e5666-7d8d-11e7-9a3b-1d0e48497986.png)

3 instances are running, the logs are below. I hope this helps.
[msviz-docker-logs.zip](https://github.com/vitalit-sib/msviz-docker/files/1213735/msviz-docker-logs.zip)

Cheers,
Lasse

**Comment by rmylonas** [comment]
Hm.. everything looks fine.
It looks like your Apache server (the frontend) is running, but without any files inside.

Let's try another command, again with CONTAINER_ID from _apache_.:

`docker exec -it CONTAINER_ID ls -la /var/www/html`

Do you see the same list of files as in _htdocs_?

**Comment by LasseLorentzen** [comment]
Weird.

running the command gived following output:
![docker](https://user-images.githubusercontent.com/21430519/29162411-a2dda672-7db9-11e7-9e4c-1a89f052a90f.png)

So not the files in htdocs.

**Comment by rmylonas** [comment]
I'm not sure how this could happen. I just tried the installation on a Windows 7 and it went OK.

Let's try to remove the images and rebuild them. Go again in the _msviz-docker-master_ folder and type the 4 following commands. Make sure you are in the folder with the _docker-compose.yml_ file:

Stop and remove images:
```
	docker-compose stop
	docker-compose rm
```	

Build and start the new images:
```
	docker-compose build
	docker-compose up -d
```

**Comment by LasseLorentzen** [comment]
I tried reinstalling but to no avail - it's the same issue.

**Comment by LasseLorentzen** [comment]
Ok, so I had an old linux laptop lying around. I installed MsViz successfully on this machine, and I guess that could do for now.  Can you maybe tell me how to set it up for remote access (i.e. the laptop acting as server) or point me to resources on how to do this?

Thank you very much,
Lasse

**Comment by rmylonas** [comment]
Hi Lasse

Concerning your problem with the Windows installation, there are other people having the [same issue](https://github.com/docker/for-win/issues/25). But it looks like there are several causes and solutions (like changing the windows password??). Did you try to run Docker as admin?

Well, it's good news that the installation worked on linux. To access MsViz from another computer (which must be on the same network though):

1. type `ip addr show` on your linux computer to get its IP address.

![ip_addr_show](https://user-images.githubusercontent.com/2772326/29171779-f5573dfe-7ddd-11e7-81fe-99663fa361ac.png)

2. access MsViz from another machine by opening the following URL in your browser:
`http://YOUR_IP_ADDRESS:9001`

3. in case it doesn't work, it might be due to your firewall settings on your linux machine.  

Please let me know if that helped.

Best,
Roman

**Comment by LasseLorentzen** [comment]
I tried some of the workarounds for the windows PC with no luck. But the linux PC is handling MsViz very well, and I actually think the current set-up is better - with the Linux PC dedicated to MsViz the windows PC can better be used for DB searches etc.

The software looks very nice from the first view. Can I ask if there's any plans to extend support to other search engines, more specifically mzid's generated through SearchGUI/Peptideshaker? 

Thank you very much for your help.
Best,
Lasse

**Comment by rmylonas** [comment]
Hi Lasse,

Yes, I think extending the supported mzid's is a good idea. I will definitely put it into our TODO list.
And please don't hesitate to ask other questions or request any further improvements.

Best,
Roman
